export const serviceElemsContent = {
    risk: `
        Know your customer – one of the most important principles when dealing with foreign and even domestic partners. No less important is knowing your suppliers and service providers. Disregarding these fundamental rules may result in financial losses, reputation damage, and compliance issues. 
        We provide a whole range of risk assessment and background security check services. Our specialists have more than 20 years of expertise in data analysis, where the digital footprint is an essential part of any security compliance.
        We will examine your business partners' history, financial condition, reputation, and licenses beyond regular open sources. 
        That allows us to present you with a comprehensive evaluation that contains all the benefits and risks you may face. Our procedures rely on several regulations and guidelines issued by the UN, WTO, and national authorities, including the United States Department of Commerce. We know the latter's importance and ensure that your and your prospective business partners' intentions and actions will not violate the rules and you will not meet any negative consequences. Using various software tools, our specialists constantly monitor upcoming policies, regulations, and geopolitical environment updates to provide valuable recommendations and decrease the potential for entering risky business deals.`,
    procurement: `
        Procurement and sourcing services play a crucial role in the supply chain and are essential for businesses to save costs, improve supplier relationships, and ensure the timely and efficient provision of goods and services. Whether you’re in retail, e-commerce, or manufacturing, procurement processes are essential to any industry. In today's world, an infinite number of producers, manufacturers, and service providers are often situated thousands of miles away from their customers. Beyond that, logistic challenges are amplified by quickly changing international situations. In these equations, businesses need trustful partners and stable supply chains.
        Through our IT solutions, we carefully screen and analyze industry news worldwide to navigate our clients in market trends that match their procurement efforts. With our SaaS and PaaS products, we can facilitate our clients' processes all the way from finding a potential manufacturer, vendor, or service provider through negotiations and pre-contracting stages to the actual execution, whether it's the provision of services, or delivery of goods to the ultimate destination. We look into manufacturers, vendors, and service providers, evaluating the reliability of their products and services not only using simple data analysis but also through arrangements of physical quality control procedures and on-site inspections. When it comes to logistics, our cloud-based solutions and AI tools can also help determine safe, commercially efficient routes through logistic hubs and ports to the ultimate destination. When it’s time to shop big for business, our procurement expertise and tailored software solutions can turn our customers' routine hassles into orderly, stressless operations.`,

    optimization: `
        Production optimization allows companies to understand and manage their production processes. This tool helps find bottlenecks, identify areas for upgrades, implement changes to increase sales, boost delivery times, and develop potential expansion plans for the future. Our software cloud solutions can efficiently monitor various performance indicators and improve production processes to achieve maximum efficiency, productivity, and profitability. 
        Our Enterprise Resource Planning (ERP) systems guarantee that our clients' resources, such as materials, labor, equipment, and facilities, are used rationally and precisely. We initiate internal audits of our clients’ production processes, collect and analyze manufacturing data, and, on this basis, identify ‘road bumps’ and inefficient operational activities. We prepare a roadmap on streamlining workflows, scheduling, upgrading technical equipment, boosting labor capacity, and implementing new technologies. By deploying the Just-In-Time (JIT) technical process, we reduce inventory costs by ensuring that materials are delivered on time. So, the products are produced only as needed. 
        Another essential feature for production optimization is the utilization of such virtual tools as “Internet of Things” (IoT) and “Artificial Intelligence” (AI). Computer control over all stages of the technological process increases the efficiency of the entire workflow, reduces errors, and enables predictive maintenance. Our software provides real-time control over production operations while addressing issues as they appear on the go. 
        We provide SaaS solutions that bring your workflows in line with modern industry regulations and manufacturing standards by enforcing standardized processes and providing tools for quality control and assurance.
        Our production optimization services are not only about boosting efficiency and cutting expenses but also about improving the environmental footprint through minimizing waste, optimizing resources, and utilizing smart energy consumption.`,

    CRM: `
        Sales pipelines and CRM (Customer Relationship Management) solutions are two integral components of successful businesses in organizing and improving sales processes. Even though these are the most popular SaaS integrations, and there are plenty of off-the-shelf products, there is always room for improvement and customization for efficiency. 
        A sales pipeline is a visual representation of your sales process. It comprises simple components such as prospecting, qualification, proposal, negotiation, and closing. However, specific stages may vary depending on the nature of the business. The purpose of a sales pipeline is to provide visibility into the sales process, helping sales teams track progress, identify chokepoints, and prioritize activities to move deals forward resourcefully. CRM is an undoubtedly efficient software tool that helps manage multiple deals and track their progress simultaneously. It provides existing and suggestive interactions with current and prospective future customers. CRM typically includes features such as contact management, sales automation, lead tracking, email integration, and reporting/analytics. 
        CRM systems centralize customer data, enabling sales teams to access information like contact details, communication history, purchase history, and preferences in one place in the most comprehensive manner. 
        Integrating your sales pipeline with CRM ensures that sales activities and customer interactions are accurately recorded and tracked, while all valuable insights into the effectiveness of the sales process to the particular focus group or a single client are in plain sight. On the other hand, ignoring sales pipelines will make your sales team ‘blind’ to the statuses of your deals and hide potential challenges that can appear during implementations. Being unprepared with communication delays and desynchronizations will slow your sales. It is essential not only to be on the same page with your client but to be beyond pages ahead. 
        We carefully analyze our clients' selling practices and relationships with their customers and partners to fine-tune our SaaS solutions for each company's specific needs. Our CRM systems are easily integrated with other business systems applications, such as email marketing platforms, accounting software, and e-commerce platforms.`,
}