export const serviceElemsContentEn = {
    risk: `
        Know your customer – one of the most important principles when dealing with foreign and even domestic partners. No less important is knowing your suppliers and service providers. Disregarding these fundamental rules may result in financial losses, reputation damage, and compliance issues. 
        We provide a whole range of risk assessment and background security check services. Our specialists have more than 20 years of expertise in data analysis, where the digital footprint is an essential part of any security compliance.
        We will examine your business partners' history, financial condition, reputation, and licenses beyond regular open sources. 
        That allows us to present you with a comprehensive evaluation that contains all the benefits and risks you may face. Our procedures rely on several regulations and guidelines issued by the UN, WTO, and national authorities, including the United States Department of Commerce. We know the latter's importance and ensure that your and your prospective business partners' intentions and actions will not violate the rules and you will not meet any negative consequences. Using various software tools, our specialists constantly monitor upcoming policies, regulations, and geopolitical environment updates to provide valuable recommendations and decrease the potential for entering risky business deals.`,
    procurement: `
        Procurement and sourcing services play a crucial role in the supply chain and are essential for businesses to save costs, improve supplier relationships, and ensure the timely and efficient provision of goods and services. Whether you’re in retail, e-commerce, or manufacturing, procurement processes are essential to any industry. In today's world, an infinite number of producers, manufacturers, and service providers are often situated thousands of miles away from their customers. Beyond that, logistic challenges are amplified by quickly changing international situations. In these equations, businesses need trustful partners and stable supply chains.
        Through our IT solutions, we carefully screen and analyze industry news worldwide to navigate our clients in market trends that match their procurement efforts. With our SaaS and PaaS products, we can facilitate our clients' processes all the way from finding a potential manufacturer, vendor, or service provider through negotiations and pre-contracting stages to the actual execution, whether it's the provision of services, or delivery of goods to the ultimate destination. We look into manufacturers, vendors, and service providers, evaluating the reliability of their products and services not only using simple data analysis but also through arrangements of physical quality control procedures and on-site inspections. When it comes to logistics, our cloud-based solutions and AI tools can also help determine safe, commercially efficient routes through logistic hubs and ports to the ultimate destination. When it’s time to shop big for business, our procurement expertise and tailored software solutions can turn our customers' routine hassles into orderly, stressless operations.`,

    optimization: `
        Production optimization allows companies to understand and manage their production processes. This tool helps find bottlenecks, identify areas for upgrades, implement changes to increase sales, boost delivery times, and develop potential expansion plans for the future. Our software cloud solutions can efficiently monitor various performance indicators and improve production processes to achieve maximum efficiency, productivity, and profitability. 
        Our Enterprise Resource Planning (ERP) systems guarantee that our clients' resources, such as materials, labor, equipment, and facilities, are used rationally and precisely. We initiate internal audits of our clients’ production processes, collect and analyze manufacturing data, and, on this basis, identify ‘road bumps’ and inefficient operational activities. We prepare a roadmap on streamlining workflows, scheduling, upgrading technical equipment, boosting labor capacity, and implementing new technologies. By deploying the Just-In-Time (JIT) technical process, we reduce inventory costs by ensuring that materials are delivered on time. So, the products are produced only as needed. 
        Another essential feature for production optimization is the utilization of such virtual tools as “Internet of Things” (IoT) and “Artificial Intelligence” (AI). Computer control over all stages of the technological process increases the efficiency of the entire workflow, reduces errors, and enables predictive maintenance. Our software provides real-time control over production operations while addressing issues as they appear on the go. 
        We provide SaaS solutions that bring your workflows in line with modern industry regulations and manufacturing standards by enforcing standardized processes and providing tools for quality control and assurance.
        Our production optimization services are not only about boosting efficiency and cutting expenses but also about improving the environmental footprint through minimizing waste, optimizing resources, and utilizing smart energy consumption.`,

    CRM: `
        Sales pipelines and CRM (Customer Relationship Management) solutions are two integral components of successful businesses in organizing and improving sales processes. Even though these are the most popular SaaS integrations, and there are plenty of off-the-shelf products, there is always room for improvement and customization for efficiency. 
        A sales pipeline is a visual representation of your sales process. It comprises simple components such as prospecting, qualification, proposal, negotiation, and closing. However, specific stages may vary depending on the nature of the business. The purpose of a sales pipeline is to provide visibility into the sales process, helping sales teams track progress, identify chokepoints, and prioritize activities to move deals forward resourcefully. CRM is an undoubtedly efficient software tool that helps manage multiple deals and track their progress simultaneously. It provides existing and suggestive interactions with current and prospective future customers. CRM typically includes features such as contact management, sales automation, lead tracking, email integration, and reporting/analytics. 
        CRM systems centralize customer data, enabling sales teams to access information like contact details, communication history, purchase history, and preferences in one place in the most comprehensive manner. 
        Integrating your sales pipeline with CRM ensures that sales activities and customer interactions are accurately recorded and tracked, while all valuable insights into the effectiveness of the sales process to the particular focus group or a single client are in plain sight. On the other hand, ignoring sales pipelines will make your sales team ‘blind’ to the statuses of your deals and hide potential challenges that can appear during implementations. Being unprepared with communication delays and desynchronizations will slow your sales. It is essential not only to be on the same page with your client but to be beyond pages ahead. 
        We carefully analyze our clients' selling practices and relationships with their customers and partners to fine-tune our SaaS solutions for each company's specific needs. Our CRM systems are easily integrated with other business systems applications, such as email marketing platforms, accounting software, and e-commerce platforms.`,
}

export const serviceElemsContentSr = {
    risk: `
    Poznavanje svog kupca – jedan od najvažnijih principa u poslovanju sa stranim, pa i domaćim partnerima. Nije manje važno poznavanje svojih dobavljača i pružalaca usluga. Zanemarivanje ovih osnovnih pravila može dovesti do finansijskih gubitaka, oštećenja reputacije i problema sa usklađenošću.
    Pružamo čitav niz usluga procene rizika i bezbednosne provere backgrounda. Naši stručnjaci imaju više od 20 godina iskustva u analizi podataka, pri čemu su digitalni tragovi (digital footprint) suštinski deo svake bezbednosne usklađenosti. Mi ćemo ispitati istoriju vaših poslovnih partnera, finansijsko stanje, reputaciju i licence izvan redovnih otvorenih izvora. To nam omogućava da vam predstavimo sveobuhvatnu procenu koja sadrži sve prednosti i rizike sa kojima se možete suočiti. Naše procedure se oslanjaju na više propisa i smernica koje su izdali UN, WTO i nacionalne vlasti, uključujući Ministarstvo trgovine Sjedinjenih Država. Znamo važnost poslednjeg i osiguravamo da vaše namere i radnje vaših budućih poslovnih partnera neće kršiti pravila i da nećete imati negativne posledice. Koristeći različite softverske alate, naš stručnjak stalno prati predstojeće politike, propise i promene geopolitičke situacije, kako bi pružio korisne preporuke i smanjio mogućnost za ulazak u rizične poslove.
    `,
    procurement: `
    Usluge nabavke i snabdevanja  igraju ključnu ulogu u lancu snabdevanja i od suštinskog su značaja za preduzeća da postignu uštede, poboljšaju odnose sa dobavljačima i obezbede blagovremeno i efikasno snabdevanje robom i uslugama. Bilo da se bavite maloprodajom, e-trgovinom ili proizvodnjom, procesi nabavke su od suštinskog značaja za svaku industriju. U današnjem svetu, beskonačan broj proizvođača i pružalaca usluga često se nalazi hiljadama milja daleko od svojih kupaca. Osim toga, logistički izazovi se umnožavaju brzim promenama međunarodne situacije. U ovim jednačinama, preduzećima su potrebni partneri od poverenja i stabilni lanci snabdevanja.
    Kroz naša IT rešenja, pažljivo pregledamo i analiziramo novine iz industrije širom sveta kako bismo usmeravali naše klijente u tržišne trendove koji odgovaraju njihovim naporima u nabavci. Sa našim SaaS i PaaS proizvodima, možemo olakšati procese naših klijenata na celom putu od pronalaženja potencijalnog proizvođača, dobavljača ili pružaoca usluga, preko pregovora i faza predugovaranja do stvarnog izvršenja, bilo da je u pitanju pružanje usluga ili isporuka robe do krajnjeg odredišta. Istražujemo proizvođače, prodavce i dobavljače usluga, procenjujući pouzdanost njihovih proizvoda i usluga ne samo koristeći jednostavnu analizu podataka već i kroz aranžmane fizičkih procedura kontrole kvaliteta i inspekcija na licu mesta. Kada je u pitanju logistika, naša rešenja zasnovana na cloudu i AI alati takođe mogu pomoći u određivanju sigurnih, komercijalno efikasnih ruta preko logističkih čvorišta i luka do krajnjih destinacija. Kada dođe vreme za veliku kupovinu za biznis, naša stručnost u oblasti nabavke i personalizovana softverska rešenja mogu da pretvore rutinske probleme naših kupaca u uredne operacije bez stresa.
    `,

    optimization: `
    Optimizacija proizvodnje omogućava kompanijama da razumeju i upravljaju svojim proizvodnim procesima. Ovaj alat pomaže u pronalaženju „uskih grla“ (chokepoints), identifikaciji oblasti za nadogradnju, implementaciji promena za povećanje prodaje, povećanju vremena isporuke i razvoju potencijalnih planova proširenja za budućnost. Naša softverska cloud rešenja mogu efikasno pratiti različite indikatore učinka i poboljšati proizvodne procese kako bi se postigla maksimalna efikasnost, produktivnost i profitabilnost.
    Naši sistemi za planiranje resursa preduzeća (Enterprise Resource Planning – ERP) garantuju da se resursi naših klijenata, kao što su materijali, radna snaga, oprema i objekti, koriste racionalno i precizno. Pokrećemo interne revizije proizvodnih procesa naših klijenata, prikupljamo i analiziramo proizvodne podatke i na osnovu toga identifikujemo „rupe na putu“ i neefikasne operativne aktivnosti. Pripremamo mapu puta za racionalizaciju tokova posla, zakazivanje, nadogradnju tehničke opreme, povećanje radnog kapaciteta i implementaciju novih tehnologija. Primenom principa Just-In-Time (JIT) smanjujemo troškove zaliha tako što obezbeđujemo da se materijali isporučuju na vreme. Dakle, proizvodi se proizvode samo po potrebi.
    Još jedna bitna karakteristika za optimizaciju proizvodnje je korišćenje takvih virtuelnih alata kao što su Internet stvari (IoT) i veštačka inteligencija (AI). Kompjuterska kontrola nad svim fazama tehnološkog procesa povećava efikasnost celokupnog toka rada, smanjuje greške i omogućava prediktivno održavanje. Naš softver pruža kontrolu nad proizvodnim operacijama u realnom vremenu i rešava probleme u pokretu, čim se pojavljuju.
    Pružamo SaaS rešenja koja usklađuju vaš tok rada sa savremenim industrijskim propisima i proizvodnim standardima primenom standardizovanih procesa i obezbeđivanjem alata za kontrolu i osiguranje kvaliteta.
    Naše usluge optimizacije proizvodnje se ne odnose samo na povećanje efikasnosti i smanjenje troškova, već i na poboljšanje ekološkog traga kroz minimiziranje otpada, optimizaciju resursa i pametnu potrošnju energije.
    `,

    CRM: `
    Prodaja i CRM (Customer Relationship Management) rešenja su dve sastavne komponente uspešnog poslovanja u organizovanju i poboljšanju vaših prodajnih procesa. Iako su ovo najpopularnije SaaS integracije, i postoji mnogo proizvoda koji se već prodaju, uvek postoji prostor za poboljšanje i prilagođavanje radi efikasnosti.
    Sales pipeline je vizuelni prikaz vašeg prodajnog procesa. Sastoji se od jednostavnih komponenti kao što su traženje, kvalifikacija, predlog, pregovaranje i zatvaranje. Međutim, određene faze mogu varirati u zavisnosti od prirode posla. Svrha prodajnog procesa je da obezbedi vidljivost procesa prodaje, pomažući prodajnim timovima da prate napredak, identifikuju „uska grla“ i odrede prioritet aktivnosti za snalažljivo napredovanje poslova.
    CRM je nesumnjivo efikasan softverski alat koji pomaže u upravljanju više poslova, a istovremeno i praćenju njihovog napredovanja. Pruža postojeće i sugestivne interakcije sa sadašnjim i potencijalnim budućim kupcima. CRM obično uključuje funkcije kao što su upravljanje kontaktima, automatizacija prodaje, praćenje potencijalnih klijenata, integracija e-maila i izveštavanje/analitika. CRM sistemi centralizuju podatke o kupcima, omogućavajući prodajnim timovima da pristupe informacijama kao što su kontakt podaci, istorija komunikacije, istorija kupovine i preferencije na jednom mestu na najsveobuhvatniji način.
    Integracija vašeg Sales Pipeline sa CRM-om obezbeđuje da se prodajne aktivnosti i interakcije sa klijentima tačno evidentiraju i prate, dok su svi korisni uvidi u efikasnost procesa prodaje određenoj fokus grupi ili jednom klijentu na vidiku. S druge strane, ignorisanje Sales Pipelines učiniće da vaš prodajni tim bude „slep“ za statuse vaših poslova i sakriće potencijalne izazove koji se mogu pojaviti tokom implementacije. Nepripremljenost, kašnjenje u komunikaciji i desinhronizacija, usporiće vašu prodaju. Od suštinskog je značaja ne samo da budete na istoj strani sa svojim klijentom, već i da budete nekoliko koraka ispred.
    Mi pažljivo analiziramo prodajne prakse naših klijenata i odnose sa njihovim klijentima i partnerima, kako bismo dobro prilagodili naša SaaS rešenja za specifične potrebe svake kompanije. Naši CRM sistemi se lako integrišu sa drugim aplikacijama poslovnih sistema, kao što su platforme za marketing putem e-maila, računovodstveni softver i platforme za e-trgovinu.
    `,
}